import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ClientProviders from "./providers/ClientProviders";

export const metadata: Metadata = {
  title: "YunusAlam Online Auctions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            {children}
          </main>
        </ClientProviders>
      </body>
    </html>
  );
}
